const ActionEnums = Object.freeze({
    APP_STATE_SET_START_GAME: "APP_STATE_SET_START_GAME",
    GAME_STATE_SET_BOARD_SIZE: "GAME_STATE_SET_BOARD_SIZE",
    GAME_STATE_SET_FOOD_POSITION: "GAME_STATE_SET_FOOD_POSITION",
    GAME_STATE_SET_SNAKE_POSITION: "GAME_STATE_SET_SNAKE_POSITION",
});

export default ActionEnums;